# Generated by Django 6.1.1 on 2026-09-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationhistory'),
        ('notifications', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, help_text='Unique key to prevent spam', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarships.scholarship'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_SCHOLARSHIP_MATCH', 'New Scholarship Match'), ('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_READY', 'Application Ready'), ('MISSING_DOCUMENT', 'Missing Document'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFICATION_REQUIRED', 'Document Verification Required'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_EXPIRING_SOON', 'Document Expiring Soon'), ('APPLICATION_STATUS_UPDATED', 'Application Status Updated'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('DEADLINE_UPCOMING', 'Deadline Upcoming'), ('DEADLINE_URGENT', 'Deadline Urgent'), ('DEADLINE_PASSED', 'Deadline Passed'), ('CHECKLIST_INCOMPLETE', 'Checklist Incomplete'), ('PROFILE_INCOMPLETE', 'Profile Incomplete'), ('NEW_HIGH_MATCH_SCHOLARSHIP', 'New High-Match Scholarship')], max_length=50),
        ),
    ]
