# Generated by Django 6.1.1 on 2026-09-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField()),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('scholarship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=100, null=True)),
                ('official_source', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('min_cgpa', models.FloatField(blank=True, null=True)),
                ('max_income', models.FloatField(blank=True, null=True)),
                ('gender_eligibility', models.CharField(blank=True, max_length=50, null=True)),
                ('state_eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('category_eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('scholarship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='scholarships.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scholarships', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scholarships.scholarship')),
            ],
            options={
                'unique_together': {('user', 'scholarship')},
            },
        ),
    ]
