# Generated by Django 6.1.1 on 2026-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED_OFFICIAL', 'Verified Official'), ('VERIFIED_SOURCE', 'Verified Source'), ('DEMO_DATA', 'Demo Data')], default='DEMO_DATA', max_length=50),
        ),
    ]
