# Generated by Django 6.1.1 on 2026-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='application_url',
            new_name='official_application_url',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='source_url',
            new_name='official_scheme_url',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
