# Generated by Django 6.1.1 on 2026-09-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('MARKSHEET', 'Marksheet'), ('INCOME_CERT', 'Income Certificate'), ('CASTE_CERT', 'Caste Certificate'), ('DOMICILE_CERT', 'Domicile Certificate'), ('BANK_DOC', 'Bank Document'), ('DISABILITY_CERT', 'Disability Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MISSING', 'Missing'), ('EXPIRED', 'Expired'), ('VERIFICATION_REQUIRED', 'Verification Required'), ('VERIFIED', 'Verified')], default='AVAILABLE', max_length=50)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_dob', models.DateField(blank=True, null=True)),
                ('extracted_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
