# Generated by Django 6.1.1 on 2026-09-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_confidence_document_extracted_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ID_PROOF', 'Personal/Identity'), ('COLLEGE_ID', 'College ID'), ('BONAFIDE', 'Bonafide'), ('INCOME_CERT', 'Income Certificate'), ('CASTE_CERT', 'Caste/Category Certificate'), ('MARKSHEET', 'Marksheet/Academic'), ('FEE_RECEIPT', 'Fee Receipt'), ('BANK_DOC', 'Bank Document'), ('DOMICILE_CERT', 'Domicile'), ('DISABILITY_CERT', 'Disability Certificate'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
